//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agrosysEntities : DbContext
    {
        public agrosysEntities()
            : base("name=agrosysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<control_acceso> control_acceso { get; set; }
        public DbSet<detalle_factura> detalle_factura { get; set; }
        public DbSet<detalle_order_de_compra> detalle_order_de_compra { get; set; }
        public DbSet<detalle_pedido_cliente> detalle_pedido_cliente { get; set; }
        public DbSet<detalle_pedido_tienda> detalle_pedido_tienda { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<envio_cliente> envio_cliente { get; set; }
        public DbSet<envio_tienda> envio_tienda { get; set; }
        public DbSet<factura> factura { get; set; }
        public DbSet<inventario> inventario { get; set; }
        public DbSet<order_de_compra> order_de_compra { get; set; }
        public DbSet<pedido_cliente> pedido_cliente { get; set; }
        public DbSet<pedido_tienda> pedido_tienda { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<tienda> tienda { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
