//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_order_de_compra
    {
        public int id_detalle_order_de_compra { get; set; }
        public Nullable<int> cantidad { get; set; }
        public int proveedor_id_proveedor { get; set; }
        public int order_de_compra_id_order_de_compra { get; set; }
        public int producto_id_producto { get; set; }
        public string precio { get; set; }
        public string subtotal { get; set; }
    
        public virtual order_de_compra order_de_compra { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
