//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int id_inventario { get; set; }
        public Nullable<int> total_productos { get; set; }
        public int proveedor_id_proveedor { get; set; }
        public int producto_id_producto { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
