//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_de_compra
    {
        public order_de_compra()
        {
            this.detalle_order_de_compra = new HashSet<detalle_order_de_compra>();
        }
    
        public int id_order_de_compra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string iva { get; set; }
        public string total { get; set; }
    
        public virtual ICollection<detalle_order_de_compra> detalle_order_de_compra { get; set; }
    }
}
