//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class tienda
    {
        public tienda()
        {
            this.empleadoes = new HashSet<empleado>();
            this.pedido_tienda = new HashSet<pedido_tienda>();
        }
    
        public int id_tienda { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<empleado> empleadoes { get; set; }
        public virtual ICollection<pedido_tienda> pedido_tienda { get; set; }
    }
}
