//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.envio_cliente = new HashSet<envio_cliente>();
            this.facturas = new HashSet<factura>();
            this.pedido_cliente = new HashSet<pedido_cliente>();
        }
    
        public int id_cliente { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string nit { get; set; }
        public string dpi { get; set; }
    
        public virtual ICollection<envio_cliente> envio_cliente { get; set; }
        public virtual ICollection<factura> facturas { get; set; }
        public virtual ICollection<pedido_cliente> pedido_cliente { get; set; }
    }
}
