//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_acceso
    {
        public int id_control_acceso { get; set; }
        public string hora { get; set; }
        public string fecha { get; set; }
        public int usuario_id_usuario { get; set; }
    }
}
