//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_order_de_compra
    {
        public int id_detalle_order_de_compra { get; set; }
        public Nullable<int> cantidad { get; set; }
        public int proveedor_id_proveedor { get; set; }
        public int order_de_compra_id_order_de_compra { get; set; }
        public int producto_id_producto { get; set; }
        public string precio { get; set; }
        public string subtotal { get; set; }
    
        public virtual order_de_compra order_de_compra { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
