//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int id_detalle_factura { get; set; }
        public string sub_total { get; set; }
        public Nullable<int> cantidad { get; set; }
        public int factura_id_factura { get; set; }
        public int producto_id_producto { get; set; }
    }
}
