//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int id_factura { get; set; }
        public string sub_total { get; set; }
        public string total { get; set; }
        public string iva { get; set; }
        public int cliente_id_cliente { get; set; }
        public int pedido_cliente_id_pedido_cliente { get; set; }
        public int pedido_cliente_cliente_id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual pedido_cliente pedido_cliente { get; set; }
    }
}
