//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int id_inventario { get; set; }
        public Nullable<int> total_productos { get; set; }
        public int proveedor_id_proveedor { get; set; }
        public int producto_id_producto { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
