//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_cliente
    {
        public pedido_cliente()
        {
            this.facturas = new HashSet<factura>();
        }
    
        public int id_pedido_cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public int cliente_id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<factura> facturas { get; set; }
    }
}
