//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.detalle_order_de_compra = new HashSet<detalle_order_de_compra>();
            this.inventarios = new HashSet<inventario>();
            this.productoes = new HashSet<producto>();
        }
    
        public int id_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string nit { get; set; }
    
        public virtual ICollection<detalle_order_de_compra> detalle_order_de_compra { get; set; }
        public virtual ICollection<inventario> inventarios { get; set; }
        public virtual ICollection<producto> productoes { get; set; }
    }
}
