//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class tienda
    {
        public tienda()
        {
            this.empleadoes = new HashSet<empleado>();
            this.pedido_tienda = new HashSet<pedido_tienda>();
        }
    
        public int id_tienda { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<empleado> empleadoes { get; set; }
        public virtual ICollection<pedido_tienda> pedido_tienda { get; set; }
    }
}
