//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string password { get; set; }
        public int rol_id_rol { get; set; }
        public int empleado_id_empleado { get; set; }
    
        public virtual rol rol { get; set; }
    }
}
